2026-01-13 12:43 - Updated: M ../../../../../.config/zsh/config/functions,

diff --git a/.config/zsh/config/functions b/.config/zsh/config/functions
--- a/.config/zsh/config/functions
+++ b/.config/zsh/config/functions
@@ -335,6 +335,24 @@ if (( ${+commands[proto]} )); then
 	ppython() {
 		proto run python -- "$@"
 	}
+
+    dumpproto() {
+        local proto_content="
+        [settings]
+        auto-install = true
+        telemetry = false
+        unstable-lockfile = true
+        auto-clean = true
+        "
+
+        if [[ -e .prototools ]]; then
+            echo ".prototools already exists! Aborting." >&2
+            return 1
+        fi
+
+        echo "$proto_content" > .prototools
+        echo ".prototools file created!"
+    }
 fi
 
 # miru
