updates

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -13,17 +13,29 @@ for script in "$BOOTSTRAP_D"/*.sh; do
     fi
 done
 
-"$BOOTSTRAP_D/install_packages.sh" || true
-"$BOOTSTRAP_D/enables.sh" || true
-"$BOOTSTRAP_D/grub_theme.sh" || true
-"$BOOTSTRAP_D/clone_nvim.sh" || true
-"$BOOTSTRAP_D/create_dirs.sh" || true
-"$BOOTSTRAP_D/set_up_docker.sh" || true
-"$BOOTSTRAP_D/source_tmux_conf.sh" || true
-"$BOOTSTRAP_D/set_up_sddm.sh" || true
-"$BOOTSTRAP_D/remove_icons.sh" || true
-"$BOOTSTRAP_D/set_up_git.sh" || true
-"$BOOTSTRAP_D/set_up_nemo.sh" || true
-"$BOOTSTRAP_D/set_up_proto.sh" || true
-"$BOOTSTRAP_D/set_up_xdg.sh" || true
-"$BOOTSTRAP_D/set_up_zen-browser.sh" || true
+scripts=(
+    "install_packages"
+    "enables"
+    "grub_theme"
+    "clone_nvim"
+    "create_dirs"
+    "set_up_docker"
+    "source_tmux_conf"
+    "set_up_sddm"
+    "remove_icons"
+    "set_up_git"
+    "set_up_nemo"
+    "set_up_proto"
+    "set_up_xdg"
+    "set_up_zen-browser"
+    "set_up_spicetify"
+)
+
+for script in "${scripts[@]}"; do
+    if [[ -f "$BOOTSTRAP_D/$script" ]]; then
+        echo "Executing: $script"
+        "$BOOTSTRAP_D/$script.sh" || true
+    else
+        echo "Warning: Script '$script' not found in $BOOTSTRAP_D" >&2
+    fi
+done
